"""add models

Revision ID: 0efb6137160f
Revises: 8cb1a8175d71
Create Date: 2025-01-09 14:46:50.029610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efb6137160f'
down_revision = '8cb1a8175d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_plan', sa.Column('estimated_budget', sa.Float(), nullable=True))
    op.add_column('travel_plan', sa.Column('actual_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_plan', 'actual_cost')
    op.drop_column('travel_plan', 'estimated_budget')
    # ### end Alembic commands ###
